apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  # This name, ca-issuer, should also be in my-ingress's metadata section.
  name: ca-issuer
  namespace: default
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: {{ .Values.cert_email }}
    privateKeySecretRef:
      name: letsencrypt-staging
    # Enable the HTTP-01 challenge provider
    solvers:
    - selector: {}
      http01:
        ingress:
          class: nginx
